<div class="side_page">
    <h2>Ajout / Suppression de Prestation</h2>
    <form action="view/php/ajax/add_service.php" method='POST'>
        <input type="text" placeholder="intitulé" name='title' required>
        <input type="text" placeholder="duré" name='time' required>
        <input type="text" placeholder="prix" name='price' required>
        <button class="button">envoyer</button>
    </form>
</div>
<div class="list">
    <?php foreach ($service as $s) : ?>
        <ul>
            <li><?= $s['title'] ?></li>
            <li><?= $s['price'] ?></li>
            <li>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18" class='service' name='<?= $s['id'] ?>'>
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path d="M17 6h5v2h-2v13a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V8H2V6h5V3a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v3zm1 2H6v12h12V8zm-9 3h2v6H9v-6zm4 0h2v6h-2v-6zM9 4v2h6V4H9z" />
                </svg>
            </li>
        </ul>
    <?php endforeach; ?>
</div>