<div class="side_page">
    <h2>Ajout / Suppression de Prestation</h2>
    <form action="index.php?page=add_service" method='POST'>
        <input type="text" placeholder="intitulé" name='title' required>
        <input type="text" placeholder="duré" name='time' required>
        <input type="text" placeholder="prix" name='price' required>
        <button class="button">envoyer</button>
    </form>
    <div class="list list_service">

    </div>
</div>