<div id="home_page">
    <div class="logo_mobile_top">
        <div class="logo_mobile_top_h1">
            <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
                <h1>bonjour <?= $_SESSION['id'] ?></h1>
            <?php else : ?>
                <h1>je vis comme je suis</h1>
            <?php endif; ?>
        </div>
        <div class="logo_top_mobile_img">
            <img src="view//img/logo-je-vis-comme-je-suis--basic.png" alt="">
        </div>
    </div>
    <div class="nav_space" id="reflexe_reiki"></div>
    <div class="first_part">
        <div class="reflexe_primitif" id="reflexe_primitif">
            <h2>réflexes primitifs</h2>
            <div class="reflexe_primitif_1">
                <h3>posture</h3>
                <ul>
                    <li>Instabilité posturale</li>
                    <li>Posture avachie ou tendue</li>
                    <li>Douleurs lombaires, cervicales</li>
                    <li>Difficulté pour l’apprentissage de la nage, du vélo </li>
                    <li>Perte d’équilibre</li>
                    <li>Mal des transports</li>
                    <li>Maladresse</li>
                    <li>Hyperactivité</li>
                </ul>
            </div>
            <div class="reflexe_primitif_2">
                <h3>émotions</h3>
                <ul>
                    <li>Difficultés émotionnelles et relationnelles</li>
                    <li>Réactions inappropriées en cas de danger</li>
                    <li>Insécurité</li>
                    <li>Manque d’estime de soi</li>
                    <li>Timidité</li>
                    <li>Troubles du sommeil</li>
                    <li>Peur des séparations</li>
                    <li>Troubles de l’alimentation</li>
                    <li>Hypersensibilité</li>
                    <li>Fatigue</li>
                    <li>Colère</li>
                </ul>
            </div>
            <div class="reflexe_primitif_3">
                <h3>cognitif</h3>
                <ul>
                    <li>Troubles cognitifs</li>
                    <li>Dyslexie</li>
                    <li>Difficultés pour recopier au tableau</li>
                    <li>Difficultés de lecture</li>
                    <li>Faible capacité de concentration</li>
                    <li>Trouble du langage</li>
                    <li>Difficultés d’écriture</li>
                </ul>
            </div>
            <p>Les <strong> réflexes primitifs</strong> sont des mouvements involontaires que l’on peut observer chez les nouveau-nés, tels que le réflexe d’agrippement palmaire par exemple. Ils vont permettre de mettre le corps en mouvement dès les premières semaines de gestation</p>
            <a class='button' href="les_réflexes_primitifs">En savoir plus</a>
        </div>
        <div class="reiki" id="reiki">
            <h2>reiki</h2>
            <div class="reiki_1">
                <h3>sur le plan physique</h3>
                <ul>
                    <li>Douleurs fantômes</li>
                    <li>Jambes lourdes y compris durant la grossesse</li>
                    <li>Meilleure respiration</li>
                    <li>Sommeil réparateur</li>
                    <li>Douleurs articulaires</li>
                    <li>Accompagnement lors de traitements lourds</li>
                </ul>
            </div>
            <div class="reiki_2">
                <h3>sur le plan émotionnel</h3>
                <ul>
                    <li>Allègement de la charge mentale</li>
                    <li>Sérénité Apaisement</li>
                    <li>Blessures du passé</li>
                    <li>Recentrage et ancrage</li>
                    <li>Estime et confiance en soi</li>
                </ul>
            </div>
            <p>Le <strong> reiki</strong> est une pratique énergétique qui vous accompagne sur un plan physique et/ou émotionnel. Par imposition des mains sur votre corps ou à distance, l’énergie Reiki vous permet de recevoir du bien-être, là où vous en avez le plus besoin sur l’instant, afin d’enclencher un processus d’auto-guérison.
            </p>
            <a class='button' href="le_reiki">En savoir plus</a>
        </div>
    </div>
    <div class="nav_space" id="qui_suis_je"></div>
    <div class="second_part">
        <h2>qui suis-je</h2>
        <div class="picture_description">
            <div class="profil_picture">
                <img src="view/img/photo.jpg" alt="profil_picture" id='profil_picture'>
            </div>
            <div class="who_i_am">
                <p>En 2017, mon chemin se concrétise pour me conduire jusqu’à l’exercice d’une activité qui me permet aujourd’hui de vous proposer un accompagnement par le bien être. Grâce à une conférence de Nita Mocanu à Bourges, je découvre ce qu’est le Reiki. C’est alors auprès de Claire Denizet que je réaliserai la totalité de ma formation, jusqu’au certificat de Maître Enseignante Reiki Usui en 2020.
                    L’année 2020, sera celle où je terminerai mon parcours de formation en Reiki pour en débuter un nouveau à l’institut Cassiopée, à Chatou, auprès de Claire Lecut, afin d’obtenir le certificat de Praticienne en Réflexes Primitifs.
                    Les deux pratiques réunies m’ont permis une transformation intérieure qui me conduit aujourd’hui à exercer pleinement une activité consacrée à l’accompagnement par des méthodes de bien-être. Grâce à mes formations et mon parcours personnel, je vous accompagne dans le respect de votre corps et de vos émotions selon l’expression de vos besoins.</p>
            </div>
        </div>
        <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
        <?php else : ?>
            <div class="connexion_toggle">
                <form action="index.php?page=connect_user" method='POST'>
                    <input id='login' title='login' name='login' type="text">
                    <input id='password' title='password' name='password' type="password">
                    <div class="connexion_toggle_button">
                        <button class='connect_user'>connexion</button>
                        <a class='close_connexion_toggle'>fermer</a>
                    </div>
                </form>
            </div>
        <?php endif; ?>
    </div>
    <div class="nav_space" id="temoignage"></div>
    <div class="third_part">
        <h2>témoignages</h2>
        <div class="reiki_view_reflexe_primitif_view">
            <div class="reiki_view">
                <h3>reiki</h3>
                <?php foreach ($review_cat_1 as $cat_1) : ?>
                    <div class="view">
                        <h4><?= $cat_1['title'] ?></h4>
                        <p><?= $cat_1['content'] ?></p>
                        <p><small><?= $cat_1['author'] ?></small></p>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="reflexe_primitif_view">
                <h3>réflexes primitifs</h3>
                <?php foreach ($review_cat_2 as $cat_2) : ?>
                    <div class="view">
                        <h4><?= $cat_2['title'] ?></h4>
                        <p><?= $cat_2['content'] ?></p>
                        <p><small><?= $cat_2['author'] ?></small></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="nav_space" id="contact"></div>
    <div class="fourth_part">
        <div class="service_contact" id="tarif_contact">
            <div class="service_part">
                <?php foreach ($service as $s) : ?>
                    <ul>
                        <li><?= $s['title'] ?> : </li>
                        <div class="time_price">
                            <li><?= $s['time'] ?></li>
                            <li><?= $s['price'] ?></li>
                        </div>
                    </ul>
                <?php endforeach; ?>
            </div>

            <div class="contact_part">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2717.664174369667!2d2.384847815611832!3d47.06643767915249!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47fa942ec839f421%3A0xef79319352c05ee1!2s130%20Av.%20de%20Saint-Amand%2C%2018000%20Bourges!5e0!3m2!1sfr!2sfr!4v1645629312305!5m2!1sfr!2sfr" width="100%" height="400px" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                <ul>
                    <li><?= $contact['name'] ?></li>
                    <li><?= $contact['address'] ?></li>
                    <li><?= $contact['code'] ?></li>
                    <li><a href="tel:+33<?= substr(str_replace(' ', '', $contact['phone']), 1); ?>"><?= $contact['phone'] ?></a></li>
                    <li><?= $contact['mail'] ?></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="social">
        <a target="_blank" href="https://www.facebook.com/Je-vis-comme-je-suis-102566288842586">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="50px" height="50px">
                <linearGradient id="awSgIinfw5_FS5MLHI~A9a" x1="6.228" x2="42.077" y1="4.896" y2="43.432" gradientUnits="userSpaceOnUse">
                    <stop offset="0" stop-color="#0d61a9" />
                    <stop offset="1" stop-color="#16528c" />
                </linearGradient>
                <path fill="url(#awSgIinfw5_FS5MLHI~A9a)" d="M42,40c0,1.105-0.895,2-2,2H8c-1.105,0-2-0.895-2-2V8c0-1.105,0.895-2,2-2h32	c1.105,0,2,0.895,2,2V40z" />
                <path d="M25,38V27h-4v-6h4v-2.138c0-5.042,2.666-7.818,7.505-7.818c1.995,0,3.077,0.14,3.598,0.208	l0.858,0.111L37,12.224L37,17h-3.635C32.237,17,32,18.378,32,19.535V21h4.723l-0.928,6H32v11H25z" opacity=".05" />
                <path d="M25.5,37.5v-11h-4v-5h4v-2.638c0-4.788,2.422-7.318,7.005-7.318c1.971,0,3.03,0.138,3.54,0.204	l0.436,0.057l0.02,0.442V16.5h-3.135c-1.623,0-1.865,1.901-1.865,3.035V21.5h4.64l-0.773,5H31.5v11H25.5z" opacity=".07" />
                <path fill="#fff" d="M33.365,16H36v-3.754c-0.492-0.064-1.531-0.203-3.495-0.203c-4.101,0-6.505,2.08-6.505,6.819V22h-4v4	h4v11h5V26h3.938l0.618-4H31v-2.465C31,17.661,31.612,16,33.365,16z" />
            </svg>
        </a>
        <a target="_blank" href="https://www.instagram.com/jeviscommejesuis18/?hl=fr">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="50px" height="50px">
                <radialGradient id="yOrnnhliCrdS2gy~4tD8ma" cx="19.38" cy="42.035" r="44.899" gradientUnits="userSpaceOnUse">
                    <stop offset="0" stop-color="#fd5" />
                    <stop offset=".328" stop-color="#ff543f" />
                    <stop offset=".348" stop-color="#fc5245" />
                    <stop offset=".504" stop-color="#e64771" />
                    <stop offset=".643" stop-color="#d53e91" />
                    <stop offset=".761" stop-color="#cc39a4" />
                    <stop offset=".841" stop-color="#c837ab" />
                </radialGradient>
                <path fill="url(#yOrnnhliCrdS2gy~4tD8ma)" d="M34.017,41.99l-20,0.019c-4.4,0.004-8.003-3.592-8.008-7.992l-0.019-20	c-0.004-4.4,3.592-8.003,7.992-8.008l20-0.019c4.4-0.004,8.003,3.592,8.008,7.992l0.019,20	C42.014,38.383,38.417,41.986,34.017,41.99z" />
                <radialGradient id="yOrnnhliCrdS2gy~4tD8mb" cx="11.786" cy="5.54" r="29.813" gradientTransform="matrix(1 0 0 .6663 0 1.849)" gradientUnits="userSpaceOnUse">
                    <stop offset="0" stop-color="#4168c9" />
                    <stop offset=".999" stop-color="#4168c9" stop-opacity="0" />
                </radialGradient>
                <path fill="url(#yOrnnhliCrdS2gy~4tD8mb)" d="M34.017,41.99l-20,0.019c-4.4,0.004-8.003-3.592-8.008-7.992l-0.019-20	c-0.004-4.4,3.592-8.003,7.992-8.008l20-0.019c4.4-0.004,8.003,3.592,8.008,7.992l0.019,20	C42.014,38.383,38.417,41.986,34.017,41.99z" />
                <path fill="#fff" d="M24,31c-3.859,0-7-3.14-7-7s3.141-7,7-7s7,3.14,7,7S27.859,31,24,31z M24,19c-2.757,0-5,2.243-5,5	s2.243,5,5,5s5-2.243,5-5S26.757,19,24,19z" />
                <circle cx="31.5" cy="16.5" r="1.5" fill="#fff" />
                <path fill="#fff" d="M30,37H18c-3.859,0-7-3.14-7-7V18c0-3.86,3.141-7,7-7h12c3.859,0,7,3.14,7,7v12	C37,33.86,33.859,37,30,37z M18,13c-2.757,0-5,2.243-5,5v12c0,2.757,2.243,5,5,5h12c2.757,0,5-2.243,5-5V18c0-2.757-2.243-5-5-5H18z" />
            </svg>
        </a>
    </div>
</div>