<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:url" content="https://jeviscommejesuis.fr/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="je vis comme je suis">
    <meta name="description" content="Accompagnement enfants adultes avec difficultés d’apprentissage, émotionnelle, posture, motricité. Développement personnel, performance sportive, musicale.">
    <meta name="google-site-verification" content="VpxKGi42lmvD2M8tMoa5gXQahJQCpRJmLbYQKyEKY1g" />
    <link rel="apple-touch-icon" sizes="180x180" href="view/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="view/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="view/img/favicon/favicon-16x16.png">
    <link rel="stylesheet" href="view/css/style.css">
    <script src="view/js/jquery.js"></script>
    <title>Je vis comme je suis - Réflexes primitifs Reiki - Bourges</title>
</head>


<body>
    <nav>
        <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
            <a href="index.php?page=add_remove_review_page">ajouter / supprimer des avis</a>
            <a href="index.php?page=add_remove_service_page">ajouter / supprimer des prestations</a>
            <a href="accueil">accueil</a>
            <a class="destroy_session">déconnexion</a>
        <?php else : ?>
            <?php if (isset($_GET['page']) && $_GET['page'] != "home") : ?>
                <a href="accueil">accueil</a>
            <?php else : ?>
                <a href="#reflexe_reiki">réflexes primitifs et reiki</a>
                <a href="#qui_suis_je">qui suis-je</a>
                <a href="#temoignage">témoignages</a>
                <a href="#contact">tarif & contact</a>
            <?php endif; ?>
            <h1><a href="accueil" class="title">je vis comme je suis</a></h1>
        <?php endif; ?>
    </nav>
    <main>
        <?php include $template . ".phtml"; ?>
        <div class="logo_bottom_page">
            <img src="view/img/logo-je-vis-comme-je-suis--basic.png" alt="logo">
        </div>
    </main>
    <div class="nav_mobile">
        <?php if (isset($_SESSION['id']) && !empty($_SESSION['id'])) : ?>
            <a href="index.php?page=add_remove_review_page">ajouter / supprimer des avis</a>
            <a href="index.php?page=add_remove_service_page">ajouter / supprimer des prestations</a>
            <a href="accueil">accueil</a>
            <a class="destroy_session">déconnexion</a>
        <?php else : ?>
            <a href="#reflexe_primitif">les réflexes primitifs</a>
            <a href="#reiki">le reiki</a>
            <a href="#qui_suis_je">qui suis-je</a>
            <a href="#temoignage">témoignages</a>
            <a href="#tarif_contact">tarif & contact</a>
        <?php endif; ?>
    </div>
    <div class="menu_mobile_button">
        <?php if (isset($_GET['page']) && $_GET['page'] != "home") : ?>
            <svg viewBox="0 0 64 64" width="30" height="30" class="back" xmlns="http://www.w3.org/2000/svg" aria-labelledby="title" aria-describedby="desc" role="img" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>Undo</title>
                <desc>A line styled icon from Orion Icon Library.</desc>
                <path stroke-width="3.5" stroke-linecap="round" stroke="#fff" fill="none" d="M3 46h44a15 15 0 0 0 15-15 15 15 0 0 0-15-15H2" data-name="layer2" stroke-linejoin="round"></path>
                <path d="M16 34L3 46l13 12" stroke-width="3.5" stroke-linecap="round" stroke="#fff" fill="none" data-name="layer1" stroke-linejoin="round"></path>
            </svg>
        <?php else : ?>
            <svg xmlns="http://www.w3.org/2000/svg" class="open_menu" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
        <?php endif; ?>
    </div>
    <script src="view/js/script.js"></script>
    <noscript>Your browser does not support JavaScript!</noscript>

</body>

</html>