<div class="more_about">
    <a class='button' href="index.php">Retour</a>
    <div class="more_about_page">
        <p>Les réflexes primitifs vont participer à la maturation du système nerveux du fœtus, puis avoir un rôle primordial pour la réalisation de la chorégraphie de naissance. Ils vont également contribuer à la maturité du système sensoriel, à la mise en place du schéma corporel, au développement des compétences motrices et à la maturité émotionnelle. Enfin, ils vont avoir un rôle protecteur par leur mise en place de mécanismes de survie. Toutes ces fondations s’organisent durant la première année de vie, nous parlons alors de réflexes qui sont intégrés. Ils ne disparaissent cependant pas, ils sont stockés de manière à être disponibles en cas de réel danger.
        </p>
        <p>Une personne qui n’a pas correctement intégré ses réflexes va avoir un seuil de tolérance au stress plus bas que la moyenne, et une insécurité intérieure qui pourra se traduire par des peurs, des phobies, ou encore de l’anxiété. A partir de ce point, plusieurs complications peuvent alors survenir, telles que des difficultés d’apprentissage, des troubles du sommeil, des problèmes relationnels, une hypersensibilité sensorielle, une agitation excessive, de l’instabilité posturale, … Les manifestations seront très variables selon les personnes et les réflexes qui ne sont pas intégrées chez elles.
        </p>
        <p>Les pédiatres testent ces réflexes à la naissance, car ils sont le reflet de l’état du système nerveux du bébé. Notre approche est différente et agit sur la partie éducative des réflexes. Nous allons avoir pour objectif à travers l’intégration des réflexes une acquisition d’un socle de sécurité solide afin que les réflexes nous soutiennent au lieu d’entraver notre développement.</p>
        <p>Les réflexes non intégrés peuvent impacter la vie scolaire puisque si mon seuil de tolérance au stress est faible, je ne peux pas me consacrer longtemps à des aspects cognitifs. Chez les enfants cela est perçu comme un grand stress permanent sans raisons appropriées, puisqu’ils sont sans cesse en hyper vigilance. Difficultés que l’on peut tout autant retrouver chez les adultes. </p>
        <p>
            <strong>A titre préventif, je propose un atelier aux futurs parents avec comme programme :
                Que sont les réflexes primitifs ?
                Présentation des réflexes fondamentaux, leurs rôles et impact sur le développement postural, émotionnel et cognitif
                Les clefs pour favoriser les différentes phases d’un réflexe primitif, bénéfique au développement postural, émotionnel et cognitif
            </strong>
        </p>
        <p class="underline">L’origine de la pratique d’intégration en réflexes primitifs</p>
        <p>Dans les années 1970, Kerstin Linde, thérapeute en Suède, s’est servie de ses qualités d’observatrice pour mettre au point une série de mouvements basée sur ce que font naturellement les nourrissons.</p>
        <p>Dans les années 1980, le Dr Harald Blomberg, psychiatre suédois, consulte Kerstin Linde pour retrouver une coordination et une stabilité altérées par la polio. Y trouvant un bénéfice, il applique alors ces mouvements sur ses propres patients, et obtient là encore de bons résultats.</p>
        <p>Ce n’est qu’en 2003, que Moira Dempsey a développé cette méthode d’intégration des réflexes, et qui a approfondi le rôle qu’ont les réflexes dans l’instauration du sentiment de sécurité et de la capacité à créer des liens affectifs.
            « Le plan physique doit être au cœur du changement, parce qu’il est le premier mode d’apprentissage du tout-petit, et qu’il pose les bases des ressources que l’on mobilise tout au long de notre vie pour apprendre » Moira Dempsey
        </p>
    </div>
</div>