<div class="more_about">
    <a class='button' href="index.php">Retour</a>
    <div class="more_about_page">
        <p>
            La <strong>séance Reiki</strong> dure entre 45 minutes et 1 heure, avec un partage verbal selon vos besoins avant et après avoir reçu l’énergie. Sont pris en compte vos ressentis et émotions que vous pouvez partager durant la séance si vous le souhaitez.
            Vous pourrez ressentir l’effet du Reiki en cours de séance et/ou après les heures et jours qui suivent. Il est recommandé de s’hydrater suite au rendez-vous, ce qui permettra au corps d’éliminer naturellement les toxines.
        </p>
        <p>Le reiki n’est ni une religion, ni un dogme, il est indépendant de toute croyance, âge ou sexe. Lors de la réception du Reiki, vous êtes allongés, habillés et cet instant n’est en aucun cas un massage.</p>
        <p>Si vous souhaitez approfondir vos connaissances sur le Reiki et le pratiquer, je vous propose <strong> la formation au premier degré</strong>, qui vous permettra dans un premier temps de pratiquer pour vous-même, puis pour les autres si vous le souhaitez.
            La formation au Reiki peut parfois approfondir nos pratiques déjà en cours. C’est ce qui s’est produit pour moi concernant l’écriture. Celle-ci s’est modifiée suite à ma première formation, j’ai alors découvert l’écriture intuitive. Celle-ci permet d’accéder à nos pensées profondes, inconscientes, par un lâcher prise afin de nous reconnecter et retrouver l’écoute de soi-même. Si vous ressentez le besoin de déposer sur papier vos pensées dans un instant de détente, je vous propose des <strong> ateliers d’écritures intuitives</strong>.</p>
        <p>Origines du Reiki :</p>
        <p>Mikao Usui (1865-1926) est le créateur du système Reiki. Après cinquante ans de pratiques spirituelles, il reste en quête de sérénité. Il décide pour la troisième fois de sa vie, de réaliser une méditation bouddhiste nommée « repentance du lotus », d’une durée de trois semaines. Il choisit de s’installer sur la petite montagne Kurama au nord de Kyoto, pour ses qualités énergétiques reconnues, ainsi que pour son animal totem, un tigre torsadé, représentant la transformation intérieure. A la suite de cette méditation, Mikao Usui ressent une énergie qui passe par ses mains. Il commence par appliquer ses mains sur son propre corps, puis en ressentant les bienfaits, il étend sa pratique aux personnes qui l’entourent.
            Mikao Usui, fonde alors l’organisation « Usui Reiki Ryoho Gakkaï » afin de donner des séances, et former d’autres personnes à cette pratique.
            Le Reiki se développera en occident, grâce à Mme Hawayo Takata et sa petite fille, qui transmirent les principes élémentaires du Reiki ainsi que des techniques simplifiées.
        </p>
    </div>
</div>